[build]
  command = "ng build --configuration production"
  publish = "dist/azzurra-makeup-artist/browser"

[functions]
  node_bundler = "esbuild"

  [functions.node_bundler_config]
    inject = ["node_modules/buffer/index.js"]
    # AGGIUNGI QUESTO: Tratta questi moduli come esterni
    external = [
      "@grpc/grpc-js",
      "@grpc/proto-loader",
      "buffer", # Anche se lo iniettiamo, a volte è utile escluderlo dal bundling
      "fs",     # Moduli Node.js built-in che non esistono nelle Edge Functions
      "path",
      "os",
      "crypto",
      "stream",
      "util",
      "http",
      "https",
      "net",
      "tls",
      "zlib"
    ]
