[build]
  command = "ng build --configuration production"
  publish = "dist/azzurra-makeup-artist/browser"

[functions]
  node_bundler = "esbuild"

  [functions.node_bundler_config]
    inject = ["node_modules/buffer/index.js"]

